
#Data set generated by "data_prep.Rmd"
bigram <- readRDS("bigram.RData")
trigram <- readRDS("trigram.RData")
quadgram <- readRDS("quadgram.RData")


#### Helper functions
show_prediction <- function(vector, n = 1) {
  if(n == 1)
    return(vector[1])
  else if(n == 2)
    return(vector[2])
  else if(n== 3)
    return(vector[3])
}

predictWord <- function (user_input){
  xclean <- removeNumbers(removePunctuation(tolower(user_input)))
  xs <- strsplit(xclean, " ")[[1]]
  
  if (length(xs)>= 3) {
    xs <- tail(xs,3)
    if (identical(character(0),head(quadgram[quadgram$first == xs[1] & quadgram$second == xs[2] & quadgram$third == xs[3], 6],1))){
      predictWord(paste(xs[2],xs[3],sep=" "))
    }
    else {
      return( head(quadgram[quadgram$first == xs[1] & quadgram$second == xs[2] & quadgram$third == xs[3], 6],1))
    }
  }
  else if (length(xs) == 2){
    xs <- tail(xs,2)
    if (identical(character(0),head(trigram[trigram$first == xs[1] & trigram$second == xs[2], 5],1))) {
      predictWord(xs[2])
    }
    else {
      return( head(trigram[trigram$first == xs[1] & trigram$second == xs[2] & trigram$third == xs[3], 5],1))
    }
  }
  else if (length(xs) == 1){
    xs <- tail(xs,1)
    if (identical(character(0),head(bigram[bigram$first == xs[1], 4],1))) { return (head("the",1))}
    else {head(bigram[bigram$first == xs[1],4],1)}
  }
  
}

clean_input <- function(input) {
  if(input == "" | is.na(input))
    return("")
  input <- tolower(input)
  input <- gsub("[0-9](?:st|nd|rd|th)", "", input, ignore.case=F, perl=T) #remove ordinal numbers
  input <- gsub("[.\\-!]", " ", input, ignore.case=F, perl=T) #remove punctuation
  input <- gsub("[^\\p{L}'\\s]+", "", input, ignore.case=F, perl=T) #remove punctuation, leaving '
  input <- gsub("^\\s+|\\s+$", "", input) #trim leading and trailing whitespace
  input <- stripWhitespace(input)
  if(input == "" | is.na(input))
    return("")
  input <- unlist(strsplit(input, " "))
  
  return(input)
}

main2 <- function(input, word = 0) {
  
  #print(input)    #for debugging
  input <- clean_input(input)
  
  if(input[1] == "") {
    output <- ""
  }
  
  else{
    output<- predictWord(input)
  }
  
  return(output)

}

shinyServer(function(input, output) {
  
  
  # Control for reactive data
  ans1 <- reactive({
    main2(input$user_input)
  })  
  
  # Output Control
  
  output$guess1 <- ans1
})

#})